### ISSUE TITLE
flock

### ISSUE THREAD

**Issue by earthgecko** [graphite-project/carbonate#19]
Great effort, whisper can be a pain.

I have always been led to believe that "Graphite will lock the Whisper file using flock() during updates so that no other Graphite process reads it mid-update and finds inconsistent data.

Unfortunately, flock() is only an advisory lock and rsync ignores it. This means that if Graphite updates a particular Whisper file while rsync is in the middle of backing it up, the backup copy might be inconsistent."  from the boys SwiftStack - @smerritt

Having looked through the code I do not see any reference to flock in anyway.  Is this just trivial because of the context of healing to local whisper file?  If so, adding an ssh key option pull request is in order for me I think.

**Comment by filippog** [comment]
hi,
thanks for carbonate! I was thinking about locking too, related to this whisper.LOCK seems to be set by carbon when `WHISPER_LOCK_WRITES` is set in graphite's config (see https://github.com/graphite-project/whisper/issues/97) however carbonate doesn't explicitly lock if I'm reading correctly so this is also possible I think:
* expand a cluster ring from N to M
* metrics start flowing to their new position in the ring
* carbon-sync is ran to sync and merge metrics
  * meanwhile the local carbon-cache also writes to the same files while carbon-sync is backfilling
* whisper files are corrupted due to lack of locking (?)

**Comment by jssjr** [comment]
@filippog - That seems accurate. I believe we want to duplicate the `WHISPER_LOCK_WRITES` directive in the carbonate config file, modify the import so we have access to `LOCK` and set it accordingly so `update_many()` calls flock before making changes. Does this sound right? Want to take a stab at a PR or should I?

**Comment by filippog** [comment]
sounds good @jssjr ! I've split this into #47 so we can followup there, I'll take a stab at a PR shortly!

**Comment by deniszh** [comment]
Fixed in https://github.com/graphite-project/carbonate/pull/71
